### PR TITLE
T25382-rebase

### PR DESCRIPTION
**Pull request by uajain**
Endless specific commit while rebasing:
* pick 84a59c43 Generate proper vapi to compile vala-based plugins
  **dropped** due to upstream change ([627c1ee](https://gitlab.gnome.org/GNOME/totem/commit/627c1ee182eaf2b394d69cd3c6ea560136b3d731))
* pick 99a3749c Import "endless-present-on-open.patch" from Endless package
  **keep** 
* pick f256031a Import "endless-add-desktop-alias.patch" from Endless package
  **keep** 
* pick f34ae515 thumbnailer: Don't use v4l2 plugin
  **drop** as already upstreamed via two commits ([here](https://gitlab.gnome.org/GNOME/totem/commit/2a381a76d57a252abd33fc71f20baa734c3b4c94) and [here](https://gitlab.gnome.org/GNOME/totem/commit/725b9e9a265473232e1e9392e9c053e30b1a5a83))
* pick 4539a1e1 Remove DBusActivatable=true
   **keep**
* pick a5b2b49f Fix make distcheck in Jenkins by removing all references to zeitgeist
  **drop** libzeitgeist completely dropped from upstream
* pick 444e6ca1 Add Transifex translation infrastructure
  **drop** as translation update
* pick e4680bb5 Commit .pot file
  **drop** as translation update
* pick 1b5187e5 bacon: Add bacon_video_widget_get_mrl
  **keep** Opened [upstream MR](https://gitlab.gnome.org/GNOME/totem/merge_requests/83)
* pick 498324d5 bacon: Redirect users to VLC when trying to play an unsupported type
  **keep** as downstream-specific patch
* pick 00bd9c36 Fix source string
  **fixup!** to 498324d5
* pick 2f06560c Update .pot file
  **drop** as translation update
* pick f1a42635 Add translation support for several new languages
  **drop** as translation update
* pick 6202b636 Latest translations from Transifex
  **drop** as translation update
* pick 20083236 Merged with downstream translations in Transifex
  **drop** as translation update
* pick 8971c1f7 Updates from Transifex
  **drop** as translation update

https://phabricator.endlessm.com/T25382

### CODE REVIEW

**Comment by uajain** [comment]
Diffs:
* [git diff -p --stat 779ee0d7b31..endlessm/master -- ':!po' ':!.tx'](https://gist.github.com/uajain/5e8a7f98251e2b952fddf4fe9f7cdf20)
(excluded transifex changes and `po` files that were backported upstream after 779ee0d7 in [gnome-3-26 branch](https://gitlab.gnome.org/GNOME/totem/commits/gnome-3-26) )

* [git diff -p --stat 5069289f..uajain/T25382-rebase](https://gist.github.com/uajain/7f9d2a3619f5b1f4c526bb466da90b7c)

**Comment by uajain** [comment]
retest this please, as I have renamed debian packaging branch as `uajain/T25382-rebase-debian`

**Comment by uajain** [comment]
retest this please

**Review by GeorgesStavracas — APPROVED** [review]
Here's my uneducated review:
 * Talking about the rebase specificaly, it is looking okay
 * Bastien has a very valid comment in [totem!83](https://gitlab.gnome.org/GNOME/totem/merge_requests/83). I think our patchset is probably wrong, and we should file a ticket to revisit it after 3.6.
 * I believe 99a3749c0b5974a281c11c821ae433d21afa214f should be considered for upstreaming.

With those concerns said, you have my approval.

**Comment by uajain** [comment]
> I believe 99a3749 should be considered for upstreaming.

Submitted upstream PR [!84](https://gitlab.gnome.org/GNOME/totem/merge_requests/84)

**Pull request merged**
